### PR TITLE
OpenMP support for TRD tracker

### PR DESCRIPTION
**Pull request by martenole**

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi  @martenole : thanks for the fixed, looks good. Btw, instead of opening a new one, you could have force-pushed the new branch onto the old PR.

**Comment by martenole** [comment]
Ok, next time then :) Thanks for the quick merge!

**Comment by davidrohr** [comment]
Sure, I need to fix one more segfault in the TPC tracking, then this can be merged to the official repo and new tag created.

@martenole : Btw: Did you split the HLTTRDTracklet word in two for the raw data and the MC labels?

**Comment by martenole** [comment]
No, this I did not yet do. I am trying to get this in now..

**Pull request merged**
